'use client';

import { AlertTriangle, Building2, Check, CreditCard, Download, KeyRound, LayoutGrid, Lightbulb, Loader2, RefreshCw, Search, Sparkles, StickyNote, Users } from 'lucide-react';
import Link from 'next/link';
import { useEffect, useMemo, useRef, useState } from 'react';
import { ErrorText, PageHeader, When } from '@/components/ui';
import Select from '@/components/ui/Select';
import type { Period, TeamReportDTO } from '@/lib/ai/team-report';
import { api, compactInr, errorText, localNow } from '@/lib/client';
import type { ActivityDTO, MemberStats } from '@/lib/services/activity';
import { ROLE_META } from '@/lib/rbac';

const CATEGORY = {
  lead: { label: 'Leads', icon: LayoutGrid },
  note: { label: 'Notes & calls', icon: StickyNote },
  ai: { label: 'AI', icon: Sparkles },
  team: { label: 'Team', icon: Users },
  workspace: { label: 'Workspace', icon: Building2 },
  billing: { label: 'Billing', icon: CreditCard },
  auth: { label: 'Sign-ins & security', icon: KeyRound },
} as const;
type Category = keyof typeof CATEGORY;

const PERIOD_LABEL: Record<Period, string> = { day: '24 hours', week: '7 days', month: '30 days' };
const RATING: Record<string, { label: string; tone: string }> = {
  standout: { label: 'Standout', tone: 'bg-success/10 text-success ring-success/25' },
  steady: { label: 'Steady', tone: 'bg-brand/10 text-brand ring-brand/20' },
  needs_attention: { label: 'Needs attention', tone: 'bg-amber-50 text-amber-700 ring-amber-200' },
  inactive: { label: 'Inactive', tone: 'bg-surface-2 text-muted ring-line' },
};

interface Props {
  viewAll: boolean;
  canGenerate: boolean;
  initial: { items: ActivityDTO[]; nextCursor: string | null };
  reports: Partial<Record<Period, TeamReportDTO>>;
  stats: Record<Period, MemberStats[]>;
}

const initialOf = (name: string) => name.slice(0, 1).toUpperCase();

export default function ActivityView({ viewAll, canGenerate, initial, reports: initialReports, stats }: Props) {
  const [period, setPeriod] = useState<Period>('week');

  return (
    <div className="space-y-6">
      <PageHeader
        title="Activity"
        subtitle={viewAll ? 'Everything that happens in your workspace, plus an AI read on how the team is doing.' : 'Everything you’ve done in this workspace.'}
        actions={
          <div className="flex rounded-2xl bg-surface-2 p-1">
            {(Object.keys(PERIOD_LABEL) as Period[]).map((p) => (
              <button key={p} onClick={() => setPeriod(p)} className={`rounded-xl px-3 py-1.5 text-xs font-semibold transition ${period === p ? 'bg-surface text-fg shadow-soft' : 'text-muted'}`}>
                {PERIOD_LABEL[p]}
              </button>
            ))}
          </div>
        }
      />
      {viewAll && <TeamReportCard period={period} canGenerate={canGenerate} initial={initialReports} />}
      <TeamTable rows={stats[period]} period={period} viewAll={viewAll} />
      <ActivityLog initial={initial} members={stats.month} viewAll={viewAll} />
    </div>
  );
}

// ---------- AI team report ----------

function TeamReportCard({ period, canGenerate, initial }: { period: Period; canGenerate: boolean; initial: Props['reports'] }) {
  const [reports, setReports] = useState(initial);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const current = reports[period];

  async function generate() {
    setBusy(true);
    setError('');
    try {
      const res = await api<{ report: TeamReportDTO }>('/api/ai/team-report', { body: { period, now: localNow() } });
      setReports((r) => ({ ...r, [period]: res.report }));
    } catch (err) {
      setError(errorText(err));
    } finally {
      setBusy(false);
    }
  }

  return (
    <section className={`card overflow-hidden ${busy ? 'ai-shimmer' : ''}`}>
      <div className="flex flex-wrap items-center gap-4 border-b border-line p-6">
        <span className="icon-tile size-12 shrink-0">
          <Sparkles className="size-5" />
        </span>
        <div className="mr-auto min-w-0">
          <h2 className="text-base font-bold">AI team report · last {PERIOD_LABEL[period]}</h2>
          <p className="text-sm text-muted">
            {current ? (
              <>
                Generated by {current.createdBy} · <When value={current.createdAt} ago /> · {current.provider}
              </>
            ) : (
              'A per-person summary of the team’s work: highlights, risks and one coaching tip each.'
            )}
          </p>
        </div>
        {canGenerate && (
          <button className={current ? 'btn-ghost' : 'btn-primary'} onClick={generate} disabled={busy}>
            {busy ? <Loader2 className="size-4 animate-spin" /> : current ? <RefreshCw className="size-4" /> : <Sparkles className="size-4" />}
            {busy ? 'Analysing team…' : current ? 'Regenerate' : 'Generate report'}
          </button>
        )}
      </div>

      {error && (
        <div className="px-6 pt-5">
          <ErrorText>{error}</ErrorText>
        </div>
      )}

      {current ? (
        <div className="space-y-6 p-6">
          <div>
            <p className="text-xl font-bold leading-snug">{current.report.headline}</p>
            <p className="mt-2 max-w-4xl text-sm leading-relaxed text-fg/80">{current.report.overview}</p>
          </div>

          <div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-3">
            {current.report.members.map((m) => {
              const r = RATING[m.rating] ?? RATING.steady;
              return (
                <article key={m.memberId} className="flex flex-col rounded-3xl bg-surface-2 p-5">
                  <div className="flex items-center gap-3">
                    <span className="grid size-10 place-items-center rounded-full bg-brand text-sm font-bold text-white">{initialOf(m.name)}</span>
                    <p className="mr-auto min-w-0 truncate font-bold">{m.name}</p>
                    <span className={`chip ${r.tone}`}>{r.label}</span>
                  </div>
                  <p className="mt-3 text-sm leading-relaxed text-fg/85">{m.summary}</p>
                  {(m.highlights.length > 0 || m.concerns.length > 0) && (
                    <ul className="mt-3 space-y-1.5 text-sm">
                      {m.highlights.map((h, i) => (
                        <li key={`h${i}`} className="flex gap-2">
                          <Check className="mt-0.5 size-4 shrink-0 text-success" /> {h}
                        </li>
                      ))}
                      {m.concerns.map((c, i) => (
                        <li key={`c${i}`} className="flex gap-2">
                          <AlertTriangle className="mt-0.5 size-4 shrink-0 text-amber-500" /> {c}
                        </li>
                      ))}
                    </ul>
                  )}
                  <p className="mt-auto flex gap-2 rounded-2xl bg-surface p-3 pt-3 text-sm [margin-top:1rem]">
                    <Lightbulb className="mt-0.5 size-4 shrink-0 text-brand-2" /> {m.suggestion}
                  </p>
                </article>
              );
            })}
          </div>

          {current.report.recommendations.length > 0 && (
            <div className="rounded-3xl bg-brand p-5 text-white">
              <p className="mb-2 text-sm font-bold">Recommended next steps for the team</p>
              <ol className="list-decimal space-y-1 pl-5 text-sm text-white/85">
                {current.report.recommendations.map((r, i) => (
                  <li key={i}>{r}</li>
                ))}
              </ol>
            </div>
          )}
        </div>
      ) : (
        !busy && (
          <p className="px-6 py-10 text-center text-sm text-muted">
            {canGenerate ? 'No report for this period yet. Generate one — it uses 1 AI action and is saved for everyone with access.' : 'No report for this period yet.'}
          </p>
        )
      )}
    </section>
  );
}

// ---------- Live per-member numbers ----------

function TeamTable({ rows, period, viewAll }: { rows: MemberStats[]; period: Period; viewAll: boolean }) {
  const sorted = [...rows].sort((a, b) => b.counts.total - a.counts.total);
  const cols: [string, (m: MemberStats) => React.ReactNode][] = [
    ['Leads added', (m) => m.counts.leadsCreated],
    ['Stage moves', (m) => m.counts.stageChanges],
    ['Won', (m) => (m.counts.won ? `${m.counts.won} · ${compactInr(m.wonValue)}` : 0)],
    ['Notes / calls', (m) => m.counts.notes + m.counts.calls + m.counts.emails],
    ['AI actions', (m) => m.counts.aiActions],
    ['Open leads', (m) => m.openLeads],
    ['Overdue', (m) => (m.overdueFollowUps ? <span className="font-bold text-rose-500">{m.overdueFollowUps}</span> : 0)],
  ];
  return (
    <section className="card overflow-hidden">
      <div className="flex items-center justify-between border-b border-line px-6 py-4">
        <h2 className="text-base font-bold">{viewAll ? 'Team at a glance' : 'Your numbers'}</h2>
        <span className="text-xs font-semibold text-muted">Last {PERIOD_LABEL[period]}</span>
      </div>
      <div className="scroll-thin overflow-x-auto">
        <table className="w-full min-w-[820px] text-sm">
          <thead className="text-left text-xs text-muted">
            <tr className="border-b border-line">
              <th className="px-6 py-3 font-semibold">Member</th>
              {cols.map(([h]) => (
                <th key={h} className="px-3 py-3 text-right font-semibold">
                  {h}
                </th>
              ))}
              <th className="px-6 py-3 text-right font-semibold">Last active</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-line">
            {sorted.map((m) => (
              <tr key={m.id} className={m.active ? '' : 'opacity-50'}>
                <td className="px-6 py-3">
                  <div className="flex items-center gap-3">
                    <span className="grid size-8 place-items-center rounded-full bg-surface-2 text-xs font-bold">{initialOf(m.name)}</span>
                    <div>
                      <p className="font-semibold">{m.name}</p>
                      <p className="text-xs text-muted">{ROLE_META[m.role].label}</p>
                    </div>
                  </div>
                </td>
                {cols.map(([h, get]) => (
                  <td key={h} className="px-3 py-3 text-right tabular-nums">
                    {get(m)}
                  </td>
                ))}
                <td className="px-6 py-3 text-right">{m.lastActive ? <When value={m.lastActive} ago /> : <span className="text-xs text-muted">Never</span>}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

// ---------- Full log ----------

const RANGES = [
  { value: '1', label: 'Last 24 hours' },
  { value: '7', label: 'Last 7 days' },
  { value: '30', label: 'Last 30 days' },
  { value: '90', label: 'Last 90 days' },
  { value: '', label: 'All time' },
];

// Server render and hydration both use India time so the markup matches; after mount we switch to the
// viewer's own time zone (see useViewerTimeZone), which can regroup items across midnight.
const SERVER_TZ = 'Asia/Kolkata';
const dayKey = (d: Date, timeZone: string) => new Intl.DateTimeFormat('en-CA', { timeZone, year: 'numeric', month: '2-digit', day: '2-digit' }).format(d);

function dayLabel(iso: string, timeZone: string) {
  const d = new Date(iso);
  const now = new Date();
  const key = dayKey(d, timeZone);
  if (key === dayKey(now, timeZone)) return 'Today';
  if (key === dayKey(new Date(now.getTime() - 86_400_000), timeZone)) return 'Yesterday';
  const sameYear = key.slice(0, 4) === dayKey(now, timeZone).slice(0, 4);
  return d.toLocaleDateString('en-IN', { timeZone, weekday: 'long', day: 'numeric', month: 'short', year: sameYear ? undefined : 'numeric' });
}

function useViewerTimeZone() {
  const [timeZone, setTimeZone] = useState(SERVER_TZ);
  useEffect(() => setTimeZone(Intl.DateTimeFormat().resolvedOptions().timeZone || SERVER_TZ), []);
  return timeZone;
}

function ActivityLog({ initial, members, viewAll }: { initial: Props['initial']; members: MemberStats[]; viewAll: boolean }) {
  const [items, setItems] = useState(initial.items);
  const [cursor, setCursor] = useState(initial.nextCursor);
  const [filters, setFilters] = useState({ actor: '', category: '', days: '', q: '' });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const first = useRef(true);

  const params = useMemo(() => {
    const sp = new URLSearchParams();
    Object.entries(filters).forEach(([k, v]) => v && sp.set(k, v));
    return sp;
  }, [filters]);

  async function load(more: boolean) {
    setLoading(true);
    setError('');
    try {
      const sp = new URLSearchParams(params);
      if (more && cursor) sp.set('before', cursor);
      const res = await api<{ items: ActivityDTO[]; nextCursor: string | null }>(`/api/activity?${sp}`);
      setItems((cur) => (more ? [...cur, ...res.items] : res.items));
      setCursor(res.nextCursor);
    } catch (err) {
      setError(errorText(err));
    } finally {
      setLoading(false);
    }
  }

  // Refetch when filters change (search is debounced).
  useEffect(() => {
    if (first.current) {
      first.current = false;
      return;
    }
    const t = setTimeout(() => load(false), filters.q ? 300 : 0);
    return () => clearTimeout(t);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [params]);

  // Leads deleted later shouldn't link to a 404.
  const deleted = useMemo(() => new Set(items.filter((i) => i.action === 'lead.deleted').map((i) => i.entity?.id)), [items]);

  const timeZone = useViewerTimeZone();
  const groups = useMemo(() => {
    const out: { day: string; rows: ActivityDTO[] }[] = [];
    for (const it of items) {
      const day = dayLabel(it.at, timeZone);
      if (out[out.length - 1]?.day === day) out[out.length - 1].rows.push(it);
      else out.push({ day, rows: [it] });
    }
    return out;
  }, [items, timeZone]);

  return (
    <section className="card overflow-hidden">
      <div className="flex flex-wrap items-center gap-2 border-b border-line px-6 py-4">
        <h2 className="mr-auto text-base font-bold">Activity log</h2>
        <div className="relative w-full sm:w-56">
          <Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted" />
          <input className="input py-2 pl-9 text-xs" placeholder="Search activity…" value={filters.q} onChange={(e) => setFilters({ ...filters, q: e.target.value })} />
        </div>
        {viewAll && (
          <Select
            size="sm"
            className="w-40"
            aria-label="Filter by member"
            value={filters.actor}
            onChange={(actor) => setFilters({ ...filters, actor })}
            options={[{ value: '', label: 'Everyone' }, ...members.map((m) => ({ value: m.id, label: m.name })), { value: 'system', label: 'System' }]}
          />
        )}
        <Select
          size="sm"
          className="w-44"
          aria-label="Filter by type"
          value={filters.category}
          onChange={(category) => setFilters({ ...filters, category })}
          options={[{ value: '', label: 'All activity' }, ...(Object.keys(CATEGORY) as Category[]).map((c) => ({ value: c, label: CATEGORY[c].label }))]}
        />
        <Select size="sm" className="w-36" aria-label="Date range" value={filters.days} onChange={(days) => setFilters({ ...filters, days })} options={RANGES} />
        <a href={`/api/activity/export?${params}`} className="btn-ghost py-2 text-xs" download>
          <Download className="size-3.5" /> CSV
        </a>
      </div>

      {error && (
        <div className="px-6 pt-4">
          <ErrorText>{error}</ErrorText>
        </div>
      )}

      <div className={`px-6 py-2 transition ${loading && !cursor ? 'opacity-60' : ''}`}>
        {groups.length === 0 && !loading && <p className="py-12 text-center text-sm text-muted">No activity matches these filters.</p>}
        {groups.map((g) => (
          <div key={g.day}>
            <p className="sticky top-0 bg-surface py-3 text-xs font-bold uppercase tracking-wider text-muted">{g.day}</p>
            <ol className="relative mb-4 space-y-1 border-l border-line pl-6">
              {g.rows.map((a) => {
                const Icon = CATEGORY[a.category]?.icon ?? LayoutGrid;
                return (
                  <li key={a.id} className="relative flex items-start gap-3 rounded-2xl py-2 pr-2">
                    <span className={`absolute -left-[37px] top-2.5 grid size-6 place-items-center rounded-full ring-4 ring-surface ${a.category === 'ai' ? 'bg-brand-2 text-white' : 'bg-surface-2 text-muted'}`}>
                      <Icon className="size-3" />
                    </span>
                    <div className="min-w-0 flex-1">
                      <p className="text-sm">
                        <b className="font-semibold">{a.actor.name}</b> <span className="text-fg/80">{lowerFirst(a.summary)}</span>
                        {a.meta?.viaSupport ? <span className="chip ml-2 bg-fg text-white ring-fg">via support</span> : null}
                      </p>
                      <p className="mt-0.5 flex flex-wrap items-center gap-x-2 text-xs text-muted">
                        <When value={a.at} />
                        {a.entity?.type === 'lead' && !deleted.has(a.entity.id) && (
                          <Link href={`/app/leads/${a.entity.id}`} className="font-semibold hover:text-brand">
                            Open lead →
                          </Link>
                        )}
                      </p>
                    </div>
                  </li>
                );
              })}
            </ol>
          </div>
        ))}
        {cursor && (
          <div className="pb-4 text-center">
            <button className="btn-ghost" onClick={() => load(true)} disabled={loading}>
              {loading ? <Loader2 className="size-4 animate-spin" /> : null} Load more
            </button>
          </div>
        )}
      </div>
    </section>
  );
}

// Summaries are written as sentences ("Moved X …"); after the actor's name they read better lowercased.
const lowerFirst = (s: string) => (/^[A-Z][a-z]/.test(s) ? s.charAt(0).toLowerCase() + s.slice(1) : s);
